"""
Ordered list of DocTypes to migrate, grouped into phases.
Phases must be migrated in order — masters before transactions, parents before children.
"""

PHASES = [
    {
        "name": "Phase 1 — Users & Roles",
        "doctypes": [
            "Role",
            "User",
            "User Permission",
            "User Role",
            "Role Profile",
            "Role Permission for Page and Report",
        ],
    },
    {
        "name": "Phase 2 — Setup & Config",
        "doctypes": [
            "Currency",
            "Currency Exchange",
            "UOM",
            "UOM Conversion Factor",
            "Item Group",
            "Customer Group",
            "Supplier Group",
            "Territory",
            "Sales Person",
            "Cost Center",
            "Warehouse Group",
            "Mode of Payment",
            "Brand",
            "Item Attribute",
            "Item Attribute Value",
            "Prospect",
        ],
    },
    {
        "name": "Phase 3 — Company & Chart of Accounts",
        "doctypes": [
            "Company",
            "Account",
            "Finance Book",
            "Fiscal Year",
            "Fiscal Year Company",
        ],
    },
    {
        "name": "Phase 4 — Operational Masters",
        "doctypes": [
            "Warehouse",
            "Price List",
            "Payment Terms",
            "Payment Terms Template",
            "Shipping Rule",
            "Shipping Rule Condition",
            "Sales Taxes and Charges Template",
            "Purchase Taxes and Charges Template",
            "Tax Category",
            "Tax Rule",
            "Terms and Conditions",
            "Letter Head",
            "Print Heading",
        ],
    },
    {
        "name": "Phase 5 — Business Masters",
        "doctypes": [
            "Address",
            "Contact",
            "Customer",
            "Supplier",
            "Item",
            "Item Price",
            "Item Barcode",
            "Item Reorder",
            "Item Tax",
            "Item Default",
            "Item Variant Settings",
            "Product Bundle",
        ],
    },
    {
        "name": "Phase 6 — HR Masters",
        "doctypes": [
            "Department",
            "Designation",
            "Branch",
            "Grade",
            "Employee Grade",
            "Employee",
            "Employee Address",
            "Employee Contact",
            "Employee Education",
            "Employee External Work History",
            "Employee Internal Work History",
            "Employee Health Insurance",
            "Appraisal Template",
        ],
    },
    {
        "name": "Phase 7 — CRM",
        "doctypes": [
            "Lead",
            "Lead Source",
            "Opportunity",
            "Opportunity Type",
            "Opportunity Item",
            "Opportunity Lost Reason",
            "Campaign",
            "Email Campaign",
            "Newsletter",
            "Newsletter Email Group",
        ],
    },
    {
        "name": "Phase 8 — Projects & Tasks",
        "doctypes": [
            "Project Type",
            "Project",
            "Task",
            "Task Type",
            "Task Depends On",
            "Timesheet",
            "Timesheet Detail",
            "Activity Type",
            "Activity Cost",
        ],
    },
    {
        "name": "Phase 9 — Support",
        "doctypes": [
            "Issue",
            "Issue Type",
            "Issue Priority",
            "Service Level Agreement",
            "Warranty Claim",
            "Maintenance Schedule",
            "Maintenance Schedule Item",
            "Maintenance Visit",
            "Maintenance Visit Purpose",
        ],
    },
    {
        "name": "Phase 10 — Quality",
        "doctypes": [
            "Quality Inspection",
            "Quality Inspection Reading",
            "Quality Action",
            "Quality Goal",
            "Quality Meeting",
            "Quality Procedure",
            "Quality Review",
        ],
    },
    {
        "name": "Phase 11 — Assets",
        "doctypes": [
            "Asset Category",
            "Asset Category Account",
            "Asset",
            "Asset Finance Book",
            "Asset Movement",
            "Asset Repair",
            "Asset Value Adjustment",
            "Location",
        ],
    },
    {
        "name": "Phase 12 — Open Transactions",
        "doctypes": [
            "BOM",
            "BOM Item",
            "BOM Operation",
            "BOM Scrap Item",
            "Material Request",
            "Material Request Item",
            "Purchase Order",
            "Purchase Order Item",
            "Sales Order",
            "Sales Order Item",
            "Quotation",
            "Quotation Item",
            "Supplier Quotation",
            "Supplier Quotation Item",
        ],
    },
    {
        "name": "Phase 13 — Completed Transactions",
        "doctypes": [
            "Purchase Receipt",
            "Purchase Receipt Item",
            "Delivery Note",
            "Delivery Note Item",
            "Purchase Invoice",
            "Purchase Invoice Item",
            "Sales Invoice",
            "Sales Invoice Item",
            "Sales Invoice Payment",
            "Payment Entry",
            "Payment Entry Reference",
            "Journal Entry",
            "Journal Entry Account",
            "Stock Entry",
            "Stock Entry Detail",
            "Stock Reconciliation",
            "Stock Reconciliation Item",
            "Landed Cost Voucher",
            "Landed Cost Item",
        ],
    },
    {
        "name": "Phase 14 — Accounting",
        "doctypes": [
            "Bank",
            "Bank Account",
            "Bank Transaction",
            "Bank Statement Import",
            "Subscription",
            "Subscription Plan",
            "Payment Request",
            "Payment Gateway Account",
            "Cheque Print Template",
            "Process Deferred Accounting",
            "Exchange Rate Revaluation",
            "Opening Invoice Creation Tool",
        ],
    },
    {
        "name": "Phase 15 — HR & Payroll",
        "doctypes": [
            "Holiday List",
            "Leave Type",
            "Leave Period",
            "Leave Policy",
            "Leave Policy Assignment",
            "Leave Allocation",
            "Leave Application",
            "Leave Encashment",
            "Compensatory Leave Request",
            "Attendance",
            "Attendance Request",
            "Shift Type",
            "Shift Assignment",
            "Employee Checkin",
            "Overtime Policy",
            "Expense Claim",
            "Expense Claim Type",
            "Expense Claim Detail",
            "Employee Advance",
            "Travel Request",
            "Employee Benefit Application",
            "Employee Benefit Claim",
            "Salary Component",
            "Salary Structure",
            "Salary Structure Assignment",
            "Salary Slip",
            "Payroll Entry",
            "Payroll Period",
            "Income Tax Slab",
            "Employee Tax Exemption Declaration",
            "Employee Tax Exemption Proof Submission",
            "Additional Salary",
            "Full and Final Statement",
            "Gratuity",
            "Appraisal",
        ],
        "requires_app": "hrms",
    },
    {
        "name": "Phase 16 — Manufacturing",
        "doctypes": [
            "Workstation",
            "Workstation Type",
            "Operation",
            "Routing",
            "Production Plan",
            "Production Plan Item",
            "Work Order",
            "Work Order Item",
            "Work Order Operation",
            "Job Card",
            "Job Card Item",
            "Job Card Operation",
            "Job Card Time Log",
        ],
    },
    {
        "name": "Phase 17 — Loan Management",
        "doctypes": [
            "Loan Type",
            "Loan",
            "Loan Application",
            "Loan Disbursement",
            "Loan Interest Accrual",
            "Loan Repayment",
            "Loan Security",
            "Loan Security Pledge",
        ],
    },
    {
        "name": "Phase 18 — Miscellaneous",
        "doctypes": [
            "Vehicle",
            "Vehicle Log",
            "Driving License Category",
            "Contract",
            "Contract Fulfilment Checklist",
            "Dunning",
            "Dunning Type",
            "QuickBooks Migrator",
        ],
    },
]

# Flat ordered list (used for preview counts)
ALL_DOCTYPES = [dt for phase in PHASES for dt in phase["doctypes"]]
